# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - master

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: metrics
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      zookeeper:
        image: bitnami/zookeeper:latest
        env:
          ALLOW_ANONYMOUS_LOGIN: "yes"
        ports:
          - 2181:2181
        # Add healthchecks
        # options: >-
        #   --health-cmd "echo ruok | nc localhost 2181 | grep imok"
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 10

      kafka:
        image: bitnami/kafka:latest
        ports:
          - 9092:9092
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_CFG_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
          KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          ALLOW_PLAINTEXT_LISTENER: "yes"
        
        # Add healthchecks
        # options: >-
        #   --health-cmd "kafka-broker-api-versions --bootstrap-server localhost:9092"
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 10

    env:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: metrics
      DB_HOST: localhost
      DB_PORT: 5432
      DB_SSLMODE: disable
      DB_INTEGRATION_DSN: postgres://postgres:postgres@localhost:5432/metrics?sslmode=disable
      KAFKA_BROKERS: localhost:9092

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'  # Можно указать 1.23, т.к. ты используешь 1.23.1 локально

      - name: Wait for services to be healthy
        run: sleep 30
          # echo "Waiting for Postgres to be ready..."
          # until pg_isready -h localhost -p 5432 -U postgres; do
          #   sleep 2
          #   echo "Waiting for Postgres..."
          # done

          # echo "Waiting for Zookeeper to be ready..."
          # until echo ruok | nc localhost 2181 | grep imok; do
          #   sleep 2
          #   echo "Waiting for Zookeeper..."
          # done

          # echo "Waiting for Kafka to be ready..."
          # until kafka-broker-api-versions --bootstrap-server localhost:9092; do
          #   sleep 2
          #   echo "Waiting for Kafka..."
          # done

      - name: Install Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Install dependencies
        run: go mod tidy

      - name: Run database migrations
        run: make migrate_up

      - name: Run integration tests
        run: make test_integration
